### ISSUE TITLE
Context isnt working

### ISSUE THREAD

**Issue by kishanhari54** [VidyasagarMSC/WatBot#10]
When i try the Conversation workspace in bluemix the response are working well, but when i try from app it doesnt seem to respond like the watson conversation does, i have set the context variables in my Child dialogs in Watson conversation service , and this code doesnt seem to send back context's.

When i try to add context in MessageOptions Builder it says Map cannot be converted to Context.

Any Idea ?

**Comment by VidyasagarMSC** [comment]
Same question is being handled on the other repo. Hence closing it here
