### ISSUE TITLE
Apk installation taking too long time

### ISSUE THREAD

**Issue by Coding-Fusion** [VidyasagarMSC/WatBot#11]
Hello Sir,

During the Gradle build, I got two error
Watson.iml could not be loaded and app.iml  not loaded.

After gradle build finished , apk is taking too long time to install in virtual device.

Please help on that.

**Comment by Coding-Fusion** [comment]
Hello.Sir, 
How to get URL or Hyperlink fetched from Watskn dialouge. only it appearss as a text

**Comment by VidyasagarMSC** [comment]
@Coding-Fusion Nothing to do with the code in the repo. Hope this link will help you https://stackoverflow.com/questions/2734270/how-do-i-make-links-in-a-textview-clickable
