### ISSUE TITLE
How to use hyperlink in the Watson Dialogue

### ISSUE THREAD

**Issue by Coding-Fusion** [VidyasagarMSC/WatBot#12]
How to use hyperlink in the Watson Dialogue. When its run in Emulator, Any link not coming as a Hyperlink

**Comment by VidyasagarMSC** [comment]
https://stackoverflow.com/questions/2734270/how-do-i-make-links-in-a-textview-clickable

**Comment by VidyasagarMSC** [comment]
@Coding-Fusion 
- Set this `Oh! you are from $location. Check <a href=https://www.google.com/maps?daddr=$location></a>` for the nearest branch._ as response in Watson Assistant Dialog 
- Add ` android:autoLink="web"` to TextView of chat_item_watson
