### ISSUE TITLE
Problem with child nodes

### ISSUE THREAD

**Issue by madavezendan** [VidyasagarMSC/WatBot#13]
Hello, I have a trouble with child nodes.  I have this situation: **Bot**:  Hello; **Me**: Hello ; **Bot**: You are welcome to my bot! **Bot**: What would you like to recommend? 
So after You are welcome to my bot! I want to skip the user input and respond with  What would you like to recommend?  This is happening in "try it out" but not in my android App..  Have you any idea how could I resolve it ?  I am using your java code for this app 

Thanks a lot!

**Comment by VidyasagarMSC** [comment]
@madavezendan Can you provide screenshots of your Dialog and also Android + Try Out?
