### ISSUE TITLE
How can i change speaker label in SpeakerLabelsDiarization class l

### ISSUE THREAD

**Issue by prokulit06** [VidyasagarMSC/WatBot#14]
I want to change speaker name into like voice 1 voice 2 is this possible or speaker is the default and i cannot change it?

**Comment by prokulit06** [comment]
please help

**Comment by prokulit06** [comment]
sir please help me sir please

**Comment by VidyasagarMSC** [comment]
Check the documentation here - https://cloud.ibm.com/docs/services/speech-to-text?topic=speech-to-text-output
