### ISSUE TITLE
how to add STT customer model

### ISSUE THREAD

**Issue by chamif1974** [VidyasagarMSC/WatBot#4]
I have created STT customer model to extend the base model. How can I integrate it in this app?

**Comment by VidyasagarMSC** [comment]
Pls. refer [https://www.ibm.com/watson/developercloud/speech-to-text/api/v1/](https://www.ibm.com/watson/developercloud/speech-to-text/api/v1/)

**Comment by chamif1974** [comment]
I know how to use the custom STT. I was looking for how we can integrate to your mobile app. May I know which call you are calling the STT service. Becos I didn't see any place you are calling the STT service URL

**Comment by VidyasagarMSC** [comment]
@chamif1974 I am using Watson developer Android & Java SDKs here.
