### ISSUE TITLE
Getting Error Gradle Entry  compile 'com.ibm.watson.developer_cloud:conversation:3.8.0'

### ISSUE THREAD

**Issue by Nimitkothari** [VidyasagarMSC/WatBot#6]
Error:FAILURE: Build failed with an exception. * What went wrong: Task 'compile' is ambiguous in root project 'WatBot-master'. Candidates are: 'compileDebugAidl', 'compileDebugAndroidTestAidl', 'compileDebugAndroidTestJavaWithJavac', 'compileDebugAndroidTestNdk', 'compileDebugAndroidTestRenderscript', 'compileDebugAndroidTestShaders', 'compileDebugAndroidTestSources', 'compileDebugJavaWithJavac', 'compileDebugNdk', 'compileDebugRenderscript', 'compileDebugShaders', 'compileDebugSources', 'compileDebugUnitTestJavaWithJavac', 'compileDebugUnitTestSources', 'compileLint', 'compileReleaseAidl', 'compileReleaseJavaWithJavac', 'compileReleaseNdk', 'compileReleaseRenderscript', 'compileReleaseShaders', 'compileReleaseSources', 'compileReleaseUnitTestJavaWithJavac', 'compileReleaseUnitTestSources'. * Try: Run gradle tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by VidyasagarMSC** [comment]
@Nimitkothari Which Android API version are you running the app? I tested on API 24 and it works well.
