### ISSUE TITLE
IllegalArgumentException: Unknown pattern character 'X'

### ISSUE THREAD

**Issue by arprasto** [VidyasagarMSC/WatBot#7]
when i am running this i am getting below error:
IllegalArgumentException: Unknown pattern character 'X'

at invoking TextToSpeech() constructor.

Can you please help here ??

when i am adding this it resolves the issue :

compile ('com.ibm.watson.developer_cloud:java-wrapper:1.1.1')

but introduces another conflict:

duplicate entry with an class file.

any help would be appreciated

**Comment by VidyasagarMSC** [comment]
@arprasto Did Gradle ran successfully? Also, what API level are you trying to run the app?

**Comment by arprasto** [comment]
Hi Vidyasagar,

I added below in Project build.gradle:
repositories {
        jcenter()
        maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
    }

and below in Module build.gradle:
compile 'com.ibm.watson.developer_cloud:text-to-speech:3.8.0'
    compile 'com.ibm.watson.developer_cloud:speech-to-text:3.8.1-SNAPSHOT'

than issue did get resolved.
