### ISSUE TITLE
Watson not communicating

### ISSUE THREAD

**Issue by Mark0l** [VidyasagarMSC/WatBot#8]
Hello, firstly thank you for your app. 
When I "Run" app to my phone, I open it and bot does not welcome me nor answers my questions. Have you ran into that kind of problem? I just edited the credentials.

**Comment by VidyasagarMSC** [comment]
@Mark0l did you create or upload a conversation dialog including intents & entities??

**Comment by Mark0l** [comment]
I created dialog myself and also tried using built-in "Car Dashboard - Sample" dialog. When I run espresso, this is what I get (pasted topic relevant errors): 
```
D/OkHttp: <-- 401 Not Authorized https://gateway.watsonplatform.net/conversation/api/v1/workspaces/74473bd5-da6e-4ea9-8526-30bfbc00ee41/message?version=2017-05-26 (193ms, unknown-length body)
E/WatsonService: POST https://gateway.watsonplatform.net/conversation/api/v1/workspaces/74473bd5-da6e-4ea9-8526-30bfbc00ee41/message?version=2017-05-26, status: 401, error: Not Authorized
``` 
I run this test on virtual phone. I verified credentials many times,

**Comment by VidyasagarMSC** [comment]
@Mark0l I just verified the code and everything is working as expected. Can you try deleting the credentials in the Watson service on IBM Cloud and re-add new credentials. 

Hope this works. I am closing this for now as it has nothing to do with the code.
