### ISSUE TITLE
cant get response of any node

### ISSUE THREAD

**Issue by razthakur** [VidyasagarMSC/WatBot#9]
When i change And Finally to Skip user input.
i dont get the text from another which i set after skip user input
while it is working in Try section of website but not working in app

**Comment by VidyasagarMSC** [comment]
Hi @razthakur, If I understand the concept of skip user input. You can skip input only if there is a child node associated with the node which you want to skip input or response from the user.

Anything_else works only if the dialog doesn't find any node matching the user response.

Can you provide info regarding your dialog to understand the issue better?

**Comment by VidyasagarMSC** [comment]
Closing this for now, you can reopen it any time.
